// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.27.1
// source: oms_order.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Order message represents the structure of an order.
type Order struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int32                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Items         []*OrderItem           `protobuf:"bytes,6,rep,name=items,proto3" json:"items,omitempty"` // List of items in the order
	CreatedAt     string                 `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	DeletedAt     string                 `protobuf:"bytes,9,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"` // Soft delete timestamp
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Order) Reset() {
	*x = Order{}
	mi := &file_oms_order_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Order) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Order) ProtoMessage() {}

func (x *Order) ProtoReflect() protoreflect.Message {
	mi := &file_oms_order_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Order.ProtoReflect.Descriptor instead.
func (*Order) Descriptor() ([]byte, []int) {
	return file_oms_order_proto_rawDescGZIP(), []int{0}
}

func (x *Order) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *Order) GetItems() []*OrderItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *Order) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Order) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *Order) GetDeletedAt() string {
	if x != nil {
		return x.DeletedAt
	}
	return ""
}

// OrderItem message represents an item in an order.
type OrderItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemId        int32                  `protobuf:"varint,3,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	Quantity      int32                  `protobuf:"varint,4,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderItem) Reset() {
	*x = OrderItem{}
	mi := &file_oms_order_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderItem) ProtoMessage() {}

func (x *OrderItem) ProtoReflect() protoreflect.Message {
	mi := &file_oms_order_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderItem.ProtoReflect.Descriptor instead.
func (*OrderItem) Descriptor() ([]byte, []int) {
	return file_oms_order_proto_rawDescGZIP(), []int{1}
}

func (x *OrderItem) GetItemId() int32 {
	if x != nil {
		return x.ItemId
	}
	return 0
}

func (x *OrderItem) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

// CreateOrderRequest is used to create an order.
type CreateOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Order         *Order                 `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrderRequest) Reset() {
	*x = CreateOrderRequest{}
	mi := &file_oms_order_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderRequest) ProtoMessage() {}

func (x *CreateOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_oms_order_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderRequest.ProtoReflect.Descriptor instead.
func (*CreateOrderRequest) Descriptor() ([]byte, []int) {
	return file_oms_order_proto_rawDescGZIP(), []int{2}
}

func (x *CreateOrderRequest) GetOrder() *Order {
	if x != nil {
		return x.Order
	}
	return nil
}

type UpdateOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       int32                  `protobuf:"varint,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"` // Order ID
	Items         []*OrderItem           `protobuf:"bytes,4,rep,name=items,proto3" json:"items,omitempty"`                     // List of items in the order
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateOrderRequest) Reset() {
	*x = UpdateOrderRequest{}
	mi := &file_oms_order_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateOrderRequest) ProtoMessage() {}

func (x *UpdateOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_oms_order_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateOrderRequest.ProtoReflect.Descriptor instead.
func (*UpdateOrderRequest) Descriptor() ([]byte, []int) {
	return file_oms_order_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateOrderRequest) GetOrderId() int32 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *UpdateOrderRequest) GetItems() []*OrderItem {
	if x != nil {
		return x.Items
	}
	return nil
}

// DeleteOrderRequest is used to delete an order.
type DeleteOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       int32                  `protobuf:"varint,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"` // Order ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteOrderRequest) Reset() {
	*x = DeleteOrderRequest{}
	mi := &file_oms_order_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteOrderRequest) ProtoMessage() {}

func (x *DeleteOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_oms_order_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteOrderRequest.ProtoReflect.Descriptor instead.
func (*DeleteOrderRequest) Descriptor() ([]byte, []int) {
	return file_oms_order_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteOrderRequest) GetOrderId() int32 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

// GetOrderRequest is used to get a specific order.
type GetOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       int32                  `protobuf:"varint,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"` // Order ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderRequest) Reset() {
	*x = GetOrderRequest{}
	mi := &file_oms_order_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderRequest) ProtoMessage() {}

func (x *GetOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_oms_order_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderRequest.ProtoReflect.Descriptor instead.
func (*GetOrderRequest) Descriptor() ([]byte, []int) {
	return file_oms_order_proto_rawDescGZIP(), []int{5}
}

func (x *GetOrderRequest) GetOrderId() int32 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

// GetAllOrdersRequest is used to get all orders.
type GetAllOrdersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllOrdersRequest) Reset() {
	*x = GetAllOrdersRequest{}
	mi := &file_oms_order_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllOrdersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllOrdersRequest) ProtoMessage() {}

func (x *GetAllOrdersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_oms_order_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllOrdersRequest.ProtoReflect.Descriptor instead.
func (*GetAllOrdersRequest) Descriptor() ([]byte, []int) {
	return file_oms_order_proto_rawDescGZIP(), []int{6}
}

// OrderResponse is the response for getting order(s).
type OrderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderResponse *OrderResponse1        `protobuf:"bytes,1,opt,name=orderResponse,proto3" json:"orderResponse,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderResponse) Reset() {
	*x = OrderResponse{}
	mi := &file_oms_order_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderResponse) ProtoMessage() {}

func (x *OrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_oms_order_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderResponse.ProtoReflect.Descriptor instead.
func (*OrderResponse) Descriptor() ([]byte, []int) {
	return file_oms_order_proto_rawDescGZIP(), []int{7}
}

func (x *OrderResponse) GetOrderResponse() *OrderResponse1 {
	if x != nil {
		return x.OrderResponse
	}
	return nil
}

// OrdersResponse is the response containing multiple orders.
type OrdersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Orders        []*Order               `protobuf:"bytes,1,rep,name=orders,proto3" json:"orders,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrdersResponse) Reset() {
	*x = OrdersResponse{}
	mi := &file_oms_order_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrdersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrdersResponse) ProtoMessage() {}

func (x *OrdersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_oms_order_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrdersResponse.ProtoReflect.Descriptor instead.
func (*OrdersResponse) Descriptor() ([]byte, []int) {
	return file_oms_order_proto_rawDescGZIP(), []int{8}
}

func (x *OrdersResponse) GetOrders() []*Order {
	if x != nil {
		return x.Orders
	}
	return nil
}

type DeleteOrderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"` // Success or error message
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteOrderResponse) Reset() {
	*x = DeleteOrderResponse{}
	mi := &file_oms_order_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteOrderResponse) ProtoMessage() {}

func (x *DeleteOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_oms_order_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteOrderResponse.ProtoReflect.Descriptor instead.
func (*DeleteOrderResponse) Descriptor() ([]byte, []int) {
	return file_oms_order_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteOrderResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Order message represents the structure of an order.
type OrderResponse1 struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Id            int32                   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        int32                   `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TotalPrice    float64                 `protobuf:"fixed64,3,opt,name=total_price,json=totalPrice,proto3" json:"total_price,omitempty"`
	Status        string                  `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	FinalPrice    float64                 `protobuf:"fixed64,5,opt,name=final_price,json=finalPrice,proto3" json:"final_price,omitempty"` // Total price after applying discounts
	Items         []*OrderItemForResponse `protobuf:"bytes,6,rep,name=items,proto3" json:"items,omitempty"`                               // List of items in the order
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderResponse1) Reset() {
	*x = OrderResponse1{}
	mi := &file_oms_order_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderResponse1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderResponse1) ProtoMessage() {}

func (x *OrderResponse1) ProtoReflect() protoreflect.Message {
	mi := &file_oms_order_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderResponse1.ProtoReflect.Descriptor instead.
func (*OrderResponse1) Descriptor() ([]byte, []int) {
	return file_oms_order_proto_rawDescGZIP(), []int{10}
}

func (x *OrderResponse1) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *OrderResponse1) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *OrderResponse1) GetTotalPrice() float64 {
	if x != nil {
		return x.TotalPrice
	}
	return 0
}

func (x *OrderResponse1) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *OrderResponse1) GetFinalPrice() float64 {
	if x != nil {
		return x.FinalPrice
	}
	return 0
}

func (x *OrderResponse1) GetItems() []*OrderItemForResponse {
	if x != nil {
		return x.Items
	}
	return nil
}

type OrderItemForResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemId        int32                  `protobuf:"varint,3,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	Quantity      int32                  `protobuf:"varint,4,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Price         float64                `protobuf:"fixed64,5,opt,name=price,proto3" json:"price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderItemForResponse) Reset() {
	*x = OrderItemForResponse{}
	mi := &file_oms_order_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderItemForResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderItemForResponse) ProtoMessage() {}

func (x *OrderItemForResponse) ProtoReflect() protoreflect.Message {
	mi := &file_oms_order_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderItemForResponse.ProtoReflect.Descriptor instead.
func (*OrderItemForResponse) Descriptor() ([]byte, []int) {
	return file_oms_order_proto_rawDescGZIP(), []int{11}
}

func (x *OrderItemForResponse) GetItemId() int32 {
	if x != nil {
		return x.ItemId
	}
	return 0
}

func (x *OrderItemForResponse) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *OrderItemForResponse) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

type AllOrderReponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Orders        []*OrderResponse1      `protobuf:"bytes,1,rep,name=orders,proto3" json:"orders,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AllOrderReponse) Reset() {
	*x = AllOrderReponse{}
	mi := &file_oms_order_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AllOrderReponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllOrderReponse) ProtoMessage() {}

func (x *AllOrderReponse) ProtoReflect() protoreflect.Message {
	mi := &file_oms_order_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllOrderReponse.ProtoReflect.Descriptor instead.
func (*AllOrderReponse) Descriptor() ([]byte, []int) {
	return file_oms_order_proto_rawDescGZIP(), []int{12}
}

func (x *AllOrderReponse) GetOrders() []*OrderResponse1 {
	if x != nil {
		return x.Orders
	}
	return nil
}

// Request message for updating the order status
type UpdateOrderStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       int32                  `protobuf:"varint,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"` // The ID of the order to be updated
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateOrderStatusRequest) Reset() {
	*x = UpdateOrderStatusRequest{}
	mi := &file_oms_order_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateOrderStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateOrderStatusRequest) ProtoMessage() {}

func (x *UpdateOrderStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_oms_order_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateOrderStatusRequest.ProtoReflect.Descriptor instead.
func (*UpdateOrderStatusRequest) Descriptor() ([]byte, []int) {
	return file_oms_order_proto_rawDescGZIP(), []int{13}
}

func (x *UpdateOrderStatusRequest) GetOrderId() int32 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

// Response message for updating the order status
type UpdateOrderStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`                                  // Success or error message
	CurrentStatus string                 `protobuf:"bytes,2,opt,name=current_status,json=currentStatus,proto3" json:"current_status,omitempty"` // The updated status of the order
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateOrderStatusResponse) Reset() {
	*x = UpdateOrderStatusResponse{}
	mi := &file_oms_order_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateOrderStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateOrderStatusResponse) ProtoMessage() {}

func (x *UpdateOrderStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_oms_order_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateOrderStatusResponse.ProtoReflect.Descriptor instead.
func (*UpdateOrderStatusResponse) Descriptor() ([]byte, []int) {
	return file_oms_order_proto_rawDescGZIP(), []int{14}
}

func (x *UpdateOrderStatusResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *UpdateOrderStatusResponse) GetCurrentStatus() string {
	if x != nil {
		return x.CurrentStatus
	}
	return ""
}

var File_oms_order_proto protoreflect.FileDescriptor

const file_oms_order_proto_rawDesc = "" +
	"\n" +
	"\x0foms_order.proto\"\x9f\x01\n" +
	"\x05Order\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x05R\x06userId\x12 \n" +
	"\x05items\x18\x06 \x03(\v2\n" +
	".OrderItemR\x05items\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\b \x01(\tR\tupdatedAt\x12\x1d\n" +
	"\n" +
	"deleted_at\x18\t \x01(\tR\tdeletedAt\"@\n" +
	"\tOrderItem\x12\x17\n" +
	"\aitem_id\x18\x03 \x01(\x05R\x06itemId\x12\x1a\n" +
	"\bquantity\x18\x04 \x01(\x05R\bquantity\"2\n" +
	"\x12CreateOrderRequest\x12\x1c\n" +
	"\x05order\x18\x01 \x01(\v2\x06.OrderR\x05order\"Q\n" +
	"\x12UpdateOrderRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\x05R\aorderId\x12 \n" +
	"\x05items\x18\x04 \x03(\v2\n" +
	".OrderItemR\x05items\"/\n" +
	"\x12DeleteOrderRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\x05R\aorderId\",\n" +
	"\x0fGetOrderRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\x05R\aorderId\"\x15\n" +
	"\x13GetAllOrdersRequest\"F\n" +
	"\rOrderResponse\x125\n" +
	"\rorderResponse\x18\x01 \x01(\v2\x0f.OrderResponse1R\rorderResponse\"0\n" +
	"\x0eOrdersResponse\x12\x1e\n" +
	"\x06orders\x18\x01 \x03(\v2\x06.OrderR\x06orders\"/\n" +
	"\x13DeleteOrderResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"\xc0\x01\n" +
	"\x0eOrderResponse1\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x05R\x06userId\x12\x1f\n" +
	"\vtotal_price\x18\x03 \x01(\x01R\n" +
	"totalPrice\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x1f\n" +
	"\vfinal_price\x18\x05 \x01(\x01R\n" +
	"finalPrice\x12+\n" +
	"\x05items\x18\x06 \x03(\v2\x15.OrderItemForResponseR\x05items\"a\n" +
	"\x14OrderItemForResponse\x12\x17\n" +
	"\aitem_id\x18\x03 \x01(\x05R\x06itemId\x12\x1a\n" +
	"\bquantity\x18\x04 \x01(\x05R\bquantity\x12\x14\n" +
	"\x05price\x18\x05 \x01(\x01R\x05price\":\n" +
	"\x0fAllOrderReponse\x12'\n" +
	"\x06orders\x18\x01 \x03(\v2\x0f.OrderResponse1R\x06orders\"5\n" +
	"\x18UpdateOrderStatusRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\x05R\aorderId\"\\\n" +
	"\x19UpdateOrderStatusResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12%\n" +
	"\x0ecurrent_status\x18\x02 \x01(\tR\rcurrentStatus2\xf8\x02\n" +
	"\fOrderService\x122\n" +
	"\vCreateOrder\x12\x13.CreateOrderRequest\x1a\x0e.OrderResponse\x127\n" +
	"\x0fUpdateOrderById\x12\x13.UpdateOrderRequest\x1a\x0f.OrderResponse1\x12<\n" +
	"\x0fDeleteOrderById\x12\x13.DeleteOrderRequest\x1a\x14.DeleteOrderResponse\x120\n" +
	"\fGetOrderById\x12\x10.GetOrderRequest\x1a\x0e.OrderResponse\x126\n" +
	"\fGetAllOrders\x12\x14.GetAllOrdersRequest\x1a\x10.AllOrderReponse\x12S\n" +
	"\x1aUpdateOrderStatusByOrderId\x12\x19.UpdateOrderStatusRequest\x1a\x1a.UpdateOrderStatusResponseB\fZ\n" +
	"./protobufb\x06proto3"

var (
	file_oms_order_proto_rawDescOnce sync.Once
	file_oms_order_proto_rawDescData []byte
)

func file_oms_order_proto_rawDescGZIP() []byte {
	file_oms_order_proto_rawDescOnce.Do(func() {
		file_oms_order_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_oms_order_proto_rawDesc), len(file_oms_order_proto_rawDesc)))
	})
	return file_oms_order_proto_rawDescData
}

var file_oms_order_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_oms_order_proto_goTypes = []any{
	(*Order)(nil),                     // 0: Order
	(*OrderItem)(nil),                 // 1: OrderItem
	(*CreateOrderRequest)(nil),        // 2: CreateOrderRequest
	(*UpdateOrderRequest)(nil),        // 3: UpdateOrderRequest
	(*DeleteOrderRequest)(nil),        // 4: DeleteOrderRequest
	(*GetOrderRequest)(nil),           // 5: GetOrderRequest
	(*GetAllOrdersRequest)(nil),       // 6: GetAllOrdersRequest
	(*OrderResponse)(nil),             // 7: OrderResponse
	(*OrdersResponse)(nil),            // 8: OrdersResponse
	(*DeleteOrderResponse)(nil),       // 9: DeleteOrderResponse
	(*OrderResponse1)(nil),            // 10: OrderResponse1
	(*OrderItemForResponse)(nil),      // 11: OrderItemForResponse
	(*AllOrderReponse)(nil),           // 12: AllOrderReponse
	(*UpdateOrderStatusRequest)(nil),  // 13: UpdateOrderStatusRequest
	(*UpdateOrderStatusResponse)(nil), // 14: UpdateOrderStatusResponse
}
var file_oms_order_proto_depIdxs = []int32{
	1,  // 0: Order.items:type_name -> OrderItem
	0,  // 1: CreateOrderRequest.order:type_name -> Order
	1,  // 2: UpdateOrderRequest.items:type_name -> OrderItem
	10, // 3: OrderResponse.orderResponse:type_name -> OrderResponse1
	0,  // 4: OrdersResponse.orders:type_name -> Order
	11, // 5: OrderResponse1.items:type_name -> OrderItemForResponse
	10, // 6: AllOrderReponse.orders:type_name -> OrderResponse1
	2,  // 7: OrderService.CreateOrder:input_type -> CreateOrderRequest
	3,  // 8: OrderService.UpdateOrderById:input_type -> UpdateOrderRequest
	4,  // 9: OrderService.DeleteOrderById:input_type -> DeleteOrderRequest
	5,  // 10: OrderService.GetOrderById:input_type -> GetOrderRequest
	6,  // 11: OrderService.GetAllOrders:input_type -> GetAllOrdersRequest
	13, // 12: OrderService.UpdateOrderStatusByOrderId:input_type -> UpdateOrderStatusRequest
	7,  // 13: OrderService.CreateOrder:output_type -> OrderResponse
	10, // 14: OrderService.UpdateOrderById:output_type -> OrderResponse1
	9,  // 15: OrderService.DeleteOrderById:output_type -> DeleteOrderResponse
	7,  // 16: OrderService.GetOrderById:output_type -> OrderResponse
	12, // 17: OrderService.GetAllOrders:output_type -> AllOrderReponse
	14, // 18: OrderService.UpdateOrderStatusByOrderId:output_type -> UpdateOrderStatusResponse
	13, // [13:19] is the sub-list for method output_type
	7,  // [7:13] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_oms_order_proto_init() }
func file_oms_order_proto_init() {
	if File_oms_order_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_oms_order_proto_rawDesc), len(file_oms_order_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_oms_order_proto_goTypes,
		DependencyIndexes: file_oms_order_proto_depIdxs,
		MessageInfos:      file_oms_order_proto_msgTypes,
	}.Build()
	File_oms_order_proto = out.File
	file_oms_order_proto_goTypes = nil
	file_oms_order_proto_depIdxs = nil
}
