/**
 * @fileoverview gRPC-Web generated client stub for 
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v3.21.12
// source: oms_users.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');

const proto = require('./oms_users_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.UserServiceClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.UserServicePromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.CreateUserRequest,
 *   !proto.User>}
 */
const methodDescriptor_UserService_CreateUser = new grpc.web.MethodDescriptor(
  '/UserService/CreateUser',
  grpc.web.MethodType.UNARY,
  proto.CreateUserRequest,
  proto.User,
  /**
   * @param {!proto.CreateUserRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.User.deserializeBinary
);


/**
 * @param {!proto.CreateUserRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.User)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.User>|undefined}
 *     The XHR Node Readable Stream
 */
proto.UserServiceClient.prototype.createUser =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/UserService/CreateUser',
      request,
      metadata || {},
      methodDescriptor_UserService_CreateUser,
      callback);
};


/**
 * @param {!proto.CreateUserRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.User>}
 *     Promise that resolves to the response
 */
proto.UserServicePromiseClient.prototype.createUser =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/UserService/CreateUser',
      request,
      metadata || {},
      methodDescriptor_UserService_CreateUser);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.GetUserRequest,
 *   !proto.User>}
 */
const methodDescriptor_UserService_GetUserById = new grpc.web.MethodDescriptor(
  '/UserService/GetUserById',
  grpc.web.MethodType.UNARY,
  proto.GetUserRequest,
  proto.User,
  /**
   * @param {!proto.GetUserRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.User.deserializeBinary
);


/**
 * @param {!proto.GetUserRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.User)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.User>|undefined}
 *     The XHR Node Readable Stream
 */
proto.UserServiceClient.prototype.getUserById =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/UserService/GetUserById',
      request,
      metadata || {},
      methodDescriptor_UserService_GetUserById,
      callback);
};


/**
 * @param {!proto.GetUserRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.User>}
 *     Promise that resolves to the response
 */
proto.UserServicePromiseClient.prototype.getUserById =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/UserService/GetUserById',
      request,
      metadata || {},
      methodDescriptor_UserService_GetUserById);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.EmptyRequestUser,
 *   !proto.GetAllUsersResponse>}
 */
const methodDescriptor_UserService_GetAllUsers = new grpc.web.MethodDescriptor(
  '/UserService/GetAllUsers',
  grpc.web.MethodType.UNARY,
  proto.EmptyRequestUser,
  proto.GetAllUsersResponse,
  /**
   * @param {!proto.EmptyRequestUser} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.GetAllUsersResponse.deserializeBinary
);


/**
 * @param {!proto.EmptyRequestUser} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.GetAllUsersResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.GetAllUsersResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.UserServiceClient.prototype.getAllUsers =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/UserService/GetAllUsers',
      request,
      metadata || {},
      methodDescriptor_UserService_GetAllUsers,
      callback);
};


/**
 * @param {!proto.EmptyRequestUser} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.GetAllUsersResponse>}
 *     Promise that resolves to the response
 */
proto.UserServicePromiseClient.prototype.getAllUsers =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/UserService/GetAllUsers',
      request,
      metadata || {},
      methodDescriptor_UserService_GetAllUsers);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.UpdateUserRequest,
 *   !proto.User>}
 */
const methodDescriptor_UserService_UpdateUserById = new grpc.web.MethodDescriptor(
  '/UserService/UpdateUserById',
  grpc.web.MethodType.UNARY,
  proto.UpdateUserRequest,
  proto.User,
  /**
   * @param {!proto.UpdateUserRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.User.deserializeBinary
);


/**
 * @param {!proto.UpdateUserRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.User)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.User>|undefined}
 *     The XHR Node Readable Stream
 */
proto.UserServiceClient.prototype.updateUserById =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/UserService/UpdateUserById',
      request,
      metadata || {},
      methodDescriptor_UserService_UpdateUserById,
      callback);
};


/**
 * @param {!proto.UpdateUserRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.User>}
 *     Promise that resolves to the response
 */
proto.UserServicePromiseClient.prototype.updateUserById =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/UserService/UpdateUserById',
      request,
      metadata || {},
      methodDescriptor_UserService_UpdateUserById);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.DeleteUserRequest,
 *   !proto.DeleteUserResponse>}
 */
const methodDescriptor_UserService_DeleteUserById = new grpc.web.MethodDescriptor(
  '/UserService/DeleteUserById',
  grpc.web.MethodType.UNARY,
  proto.DeleteUserRequest,
  proto.DeleteUserResponse,
  /**
   * @param {!proto.DeleteUserRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.DeleteUserResponse.deserializeBinary
);


/**
 * @param {!proto.DeleteUserRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.DeleteUserResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.DeleteUserResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.UserServiceClient.prototype.deleteUserById =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/UserService/DeleteUserById',
      request,
      metadata || {},
      methodDescriptor_UserService_DeleteUserById,
      callback);
};


/**
 * @param {!proto.DeleteUserRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.DeleteUserResponse>}
 *     Promise that resolves to the response
 */
proto.UserServicePromiseClient.prototype.deleteUserById =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/UserService/DeleteUserById',
      request,
      metadata || {},
      methodDescriptor_UserService_DeleteUserById);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.GetUserRequest,
 *   !proto.UserOrderResponse>}
 */
const methodDescriptor_UserService_GetUserOrdersByUserId = new grpc.web.MethodDescriptor(
  '/UserService/GetUserOrdersByUserId',
  grpc.web.MethodType.UNARY,
  proto.GetUserRequest,
  proto.UserOrderResponse,
  /**
   * @param {!proto.GetUserRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.UserOrderResponse.deserializeBinary
);


/**
 * @param {!proto.GetUserRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.UserOrderResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.UserOrderResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.UserServiceClient.prototype.getUserOrdersByUserId =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/UserService/GetUserOrdersByUserId',
      request,
      metadata || {},
      methodDescriptor_UserService_GetUserOrdersByUserId,
      callback);
};


/**
 * @param {!proto.GetUserRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.UserOrderResponse>}
 *     Promise that resolves to the response
 */
proto.UserServicePromiseClient.prototype.getUserOrdersByUserId =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/UserService/GetUserOrdersByUserId',
      request,
      metadata || {},
      methodDescriptor_UserService_GetUserOrdersByUserId);
};


module.exports = proto;

